# Set-up

In [1]:
import pandas as pd
import numpy as np

In [2]:
from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):

    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles. Determines return value units.
    return c * r

In [3]:
traffic_image=pd.read_csv('traffic_image.csv')
traffic_incidents=pd.read_csv('traffic_incidents.csv')
traffic_speed=pd.read_csv('traffic_speed.csv')
weather=pd.read_csv('weather.csv')

In [12]:
traffic_image['key']=0
traffic_incidents['key']=0
weather['key']=0

In [10]:
nearest_incidents=traffic_image.merge(traffic_incidents,'outer','key')
nearest_incidents['distance_from_id']=(np.vectorize(haversine)(nearest_incidents['Latitude_x'],nearest_incidents['Longitude_x'],nearest_incidents['Latitude_y'],nearest_incidents['Longitude_y']))*1000
nearest_incidents=nearest_incidents[nearest_incidents['distance_from_id']<500].sort_values('distance_from_id')
nearest_incidents

,CameraID,Latitude_x,Longitude_x,ImageLink,key,Type,Latitude_y,Longitude_y,Message,distance_from_id
0,1001,1.295313,103.871146,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Roadwork,1.306733,103.872351,(24/10)18:41 Roadworks on KPE (towards TPE) at...,332.638705
6,1004,1.319536,103.875067,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Roadwork,1.306733,103.872351,(24/10)18:41 Roadworks on KPE (towards TPE) at...,455.734008
4,1003,1.323957,103.872858,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Roadwork,1.306733,103.872351,(24/10)18:41 Roadworks on KPE (towards TPE) at...,462.639833

In [20]:
nearest_weather=traffic_image.merge(weather,'outer','key')
nearest_weather['distance_from_id']=(np.vectorize(haversine)(nearest_weather['Latitude'],nearest_weather['Longitude'],nearest_weather['latitude'],nearest_weather['longitude']))*1000
nearest_weather=nearest_weather.sort_values('distance_from_id').groupby('CameraID').head(1).sort_values('distance_from_id')
nearest_weather

,CameraID,Latitude,Longitude,ImageLink,key,name,latitude,longitude,timestamp,rainfall in mm,distance_from_id
829,1701,1.323605,103.858780,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Towner Road,1.32140,103.85770,2022-10-24 20:10:00+08:00,0,133.698752
2257,3795,1.301451,103.910596,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Marine Parade Road,1.30648,103.91040,2022-10-24 20:10:00+08:00,0,136.183744
2882,4706,1.297920,103.782050,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Kent Ridge Road,1.29230,103.78150,2022-10-24 20:10:00+08:00,0,160.942668
1504,2702,1.445554,103.768340,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,WOODLANDS CENTRE ROAD,1.44003,103.76904,2022-10-24 20:10:00+08:00,0,165.639227
4676,6713,1.340298,103.945652,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Simei Avenue,1.34370,103.94440,2022-10-24 20:10:00+08:00,0,166.408668
...,...,...,...,...,...,...,...,...,...,...,...
5462,8702,1.390590,103.771700,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Bukit Panjang Road,1.38240,103.76030,2022-10-24 20:10:00+08:00,0,1286.011941
579,1503,1.270664,103.856978,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Nicoll Highway,1.30105,103.86660,2022-10-24 20:10:00+08:00,0,1341.642043
1896,2708,1.386500,103.774700,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Clementi Road,1.33370,103.77680,2022-10-24 20:10:00+08:00,0,1417.405530
1556,2703,1.350478,103.791034,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Mandai Lake Road,1.40440,103.78962,2022-10-24 20:10:00+08:00,0,1437.848134
4974,7793,1.377047,103.929470,https://dm-traffic-camera-itsc.s3.ap-southeast...,0,Chai Chee Street,1.32300,103.92170,2022-10-24 20:10:00+08:00,0,1684.716327

In [21]:
traffic_speed

,LinkID,RoadName,RoadCategory,SpeedBand,MinimumSpeed,MaximumSpeed,Location,start_latitude,start_longitude,end_latitude,end_longitude
0,103000000,KENT ROAD,E,2,10,19,1.3170142376560023 103.85298052044503 1.316684...,1.317014,103.852981,1.316684,103.852599
1,103000010,BUCKLEY ROAD,E,2,10,19,1.3166507852203482 103.84102305136321 1.316912...,1.316651,103.841023,1.316912,103.840226
2,103000011,BUCKLEY ROAD,E,2,10,19,1.316912438354752 103.84022564204443 1.3166507...,1.316912,103.840226,1.316651,103.841023
3,103000014,SHREWSBURY ROAD,E,5,40,49,1.3186726294030418 103.84700267615683 1.318021...,1.318673,103.847003,1.318021,103.847114
4,103000015,SHREWSBURY ROAD,E,5,40,49,1.3180212058893457 103.84711392225329 1.318672...,1.318021,103.847114,1.318673,103.847003
...,...,...,...,...,...,...,...,...,...,...,...
495,103001218,DRAYCOTT DRIVE,D,8,70,999,1.3096279339357806 103.83110989321554 1.309694...,1.309628,103.831110,1.309695,103.831194
496,103001219,DRAYCOTT DRIVE,D,2,10,19,1.309694857000047 103.83119447352243 1.3096279...,1.309695,103.831194,1.309628,103.831110
497,103001226,PADANG JERINGAU,D,4,30,39,1.3099051585628567 103.86554520014256 1.309253...,1.309905,103.865545,1.309254,103.866117
498,103001227,PADANG JERINGAU,D,4,30,39,1.309253800591554 103.86611733337693 1.3099051...,1.309254,103.866117,1.309905,103.865545
499,103001230,GUILLEMARD CRESCENT,E,5,40,49,1.309221657875194 103.88033745809436 1.3093222...,1.309222,103.880337,1.309322,103.880871

In [7]:
df=pd.read_csv('traffic_image_region.csv')
df

    CameraID  Latitude   Longitude   Region
0       1001  1.295313  103.871146  Central
1       1002  1.319541  103.878563  Central
2       1003  1.323957  103.872858  Central
3       1004  1.319536  103.875067  Central
4       1005  1.363520  103.905394     East
..       ...       ...         ...      ...
82      9702  1.394741  103.817971    North
83      9703  1.422857  103.773005    North
84      9704  1.422143  103.795421    North
85      9705  1.426277  103.787166    North
86      9706  1.412701  103.806427    North

[87 rows x 4 columns]