In [2]:
import requests
import pandas as pd
import numpy as np
import urllib.request

In [3]:
traffic_image_url='http://datamall2.mytransport.sg/ltaodataservice/Traffic-Imagesv2'
headers_val={'AccountKey':'AO4qMbK3S7CWKSlplQZqlA=='}
traffic_image_req=requests.get(url=traffic_image_url,headers=headers_val)
traffic_image_df=pd.DataFrame(eval(traffic_image_req.content)['value'])

# downloads all the latest photos.
# traffic_image_df.apply(lambda x: urllib.request.urlretrieve(x['ImageLink'],'%s.jpg'%x['CameraID']) ,axis=1)

In [4]:
traffic_speed_url='http://datamall2.mytransport.sg/ltaodataservice/TrafficSpeedBandsv2'
traffic_speed_req=requests.get(url=traffic_speed_url,headers=headers_val)
traffic_speed_df=pd.DataFrame(eval(traffic_speed_req.content)['value'])

# road category 
# A – Expressways
# B – Major Arterial Roads
# C – Arterial Roads
# D – Minor Arterial Roads
# E – Small Roads
# F – Slip Roads
# G – No category info available

# speed bands
# 1 – indicates speed range from 0 < 9
# 2 – indicates speed range from 10 < 19
# 3 – indicates speed range from 20 < 29
# 4 – indicates speed range from 30 < 39
# 5 – indicates speed range from 40 < 49
# 6 – indicates speed range from 50 < 59
# 7 – indicates speed range from 60 < 69
# 8 – speed range from 70 or more

In [5]:
def location_splitter(location):
    location=location.split(' ')
    return location[0],location[1],location[2],location[3]

In [6]:
traffic_speed_df['start_latitude'],traffic_speed_df['start_longitude'],traffic_speed_df['end_latitude'],traffic_speed_df['end_longitude']=np.vectorize(location_splitter)(traffic_speed_df['Location'])

In [26]:
traffic_incidents_url='http://datamall2.mytransport.sg/ltaodataservice/TrafficIncidents'
traffic_incidents_req=requests.get(url=traffic_incidents_url,headers=headers_val)
traffic_incidents_df=pd.DataFrame(eval(traffic_incidents_req.content)['value'])

# NEA API
For some reason this one need to constantly call and keep track of previous results. Sometimes calls does not return all data.
Some names are given as S123, etc, looking to try OneMap reverse geocoding to get road name from lat long.

location name, no road name 
S201
S202
S203
S204
S205
S207
S208
S209
S210
S211
S212
S214
S216
S217
S219
S220
S222
S224
S226
S227
S228
S230

In [27]:
# weather_df=pd.read_csv('weather.csv')
weatherreq=requests.get(url='https://api.data.gov.sg/v1/environment/rainfall')

new_weather_df=pd.DataFrame(eval(weatherreq.content)['metadata']['stations'])

new_weather_df['latitude']=new_weather_df['location'].apply(lambda x: x['latitude'])
new_weather_df['longitude']=new_weather_df['location'].apply(lambda x: x['longitude'])
new_weather_df['timestamp']=eval(weatherreq.content)['items'][0]['timestamp']
new_weather_df['timestamp']=pd.to_datetime(new_weather_df['timestamp'])

station_rainfall=pd.DataFrame(eval(weatherreq.content)['items'][0]['readings']).rename(columns={'value':'rainfall in mm'})

new_weather_df=new_weather_df.merge(station_rainfall,how='left',left_on='id',right_on='station_id')
new_weather_df=new_weather_df.drop(['id','device_id','station_id','location'],axis=1)

# pd.concat([new_weather_df,weather_df]).drop_duplicates().to_csv('weather.csv',index=False)

# Onemap (to get road name from lat long (WIP)

In [17]:
onemapTokenAPIResponse=requests.post('https://developers.onemap.sg/privateapi/auth/post/getToken',json={'email':'leejin@u.nus.edu','password':'Whysohardtochange123!'})#.content
onemapAPItoken=eval(onemapTokenAPIResponse.content)['access_token']

In [30]:
onemapResponse=requests.get('https://developers.onemap.sg/privateapi/commonsvc/revgeocode?location=%s,%s&token=%s&buffer=100&addressType=all'%(str(1.32311),str(103.76714),onemapAPItoken))
# onemapResponse=requests.get('https://developers.onemap.sg/privateapi/commonsvc/revgeocode?location=1.3,103.8&token=0v9hsciobp1ifa5bgpkin21cs3&buffer=100&addressType=all

In [42]:
pd.DataFrame(eval(onemapResponse.content)['GeocodeInfo'])['ROAD'].mode()[0]

'SUNSET WAY'

In [43]:
def roadnamegrabber(name,latitude,longitude):
    if name[0]=='S' and len(name)<5:
        tempResponse=requests.get('https://developers.onemap.sg/privateapi/commonsvc/revgeocode?location=%s,%s&token=%s&buffer=100&addressType=all'%(str(latitude),str(longitude),onemapAPItoken))
        name=pd.DataFrame(eval(tempResponse.content)['GeocodeInfo'])['ROAD'].mode()[0]
    return name

In [44]:
new_weather_df['name']=np.vectorize(roadnamegrabber)(new_weather_df['name'],new_weather_df['latitude'],new_weather_df['longitude'])

In [45]:
new_weather_df.loc[25:51,:]

,name,latitude,longitude,timestamp,rainfall in mm
25,SUNSET WAY,1.32311,103.76714,2022-10-17 00:25:00+08:00,0
26,WEST COAST ROAD,1.30968,103.75780,2022-10-17 00:25:00+08:00,0
27,PASIR PANJANG ROAD,1.29164,103.77020,2022-10-17 00:25:00+08:00,0
28,TAMPINES EXPRESSWAY,1.40081,103.88217,2022-10-17 00:25:00+08:00,0
29,SENGKANG EAST DRIVE,1.38829,103.91160,2022-10-17 00:25:00+08:00,0
30,KOH SEK LIM ROAD,1.32485,103.95836,2022-10-17 00:25:00+08:00,0
31,CHANGI EAST CLOSE,1.31360,104.00317,2022-10-17 00:25:00+08:00,0
32,YISHUN STREET 41,1.42111,103.84472,2022-10-17 00:25:00+08:00,0
33,WOODLANDS CENTRE ROAD,1.44003,103.76904,2022-10-17 00:25:00+08:00,0
34,KRANJI ROAD,1.42918,103.75711,2022-10-17 00:25:00+08:00,0
35,SENNETT AVENUE,1.31835,103.93574,2022-10-17 00:25:00+08:00,0
36,BUKIT TIMAH ROAD,1.32427,103.80970,2022-10-17 00:25:00+08:00,0
37,TANJONG RHU ROAD,1.29911,103.88289,2022-10-17 00:25:00+08:00,0
38,ANG MO KIO AVENUE 10,1.36019,103.85335,2022-10-17 00:25:00+08:00,0
39,BISHAN STREET 13,1.35041,103.85526,2022-10-17 00:25:00+08:00,0
40,BUKIT BATOK STREET 34,1.36491,103.75065,2022-10-17 00:25:00+08:00,0
41,SELETAR GREEN WALK,1.37999,103.87643,2022-10-17 00:25:00+08:00,0
42,COMPASSVALE LANE,1.38666,103.89797,2022-10-17 00:25:00+08:00,0
43,HOUGANG STREET 22,1.35691,103.89088,2022-10-17 00:25:00+08:00,0
44,ALEXANDRA ROAD,1.28987,103.82364,2022-10-17 00:25:00+08:00,0
45,MARGARET DRIVE,1.29984,103.80264,2022-10-17 00:25:00+08:00,0
46,UNNAMED ROAD,1.34392,103.98409,2022-10-17 00:25:00+08:00,0
47,MALAN ROAD,1.27472,103.80389,2022-10-17 00:25:00+08:00,0
48,WOODLANDS DRIVE 62,1.43944,103.80389,2022-10-17 00:25:00+08:00,0
49,JURONG WEST STREET 73,1.34703,103.70073,2022-10-17 00:25:00+08:00,0
50,JURONG WEST AVENUE 1,1.35167,103.72195,2022-10-17 00:25:00+08:00,0
51,CLEMENTI WEST STREET 2,1.30167,103.76444,2022-10-17 00:25:00+08:00,0

In [46]:
# Downloads all the csv files
traffic_image_df.to_csv('traffic_image.csv',index=False)
traffic_speed_df.to_csv('traffic_speed.csv',index=False)
traffic_incidents_df.to_csv('traffic_incidents.csv',index=False)
new_weather_df.to_csv('weather.csv',index=False)

# END

In [ ]:
# id_options=[]
# for i in traffic_image_df['CameraID']:
#     temp={'label':'id%s'%str(i),'value':i}
#     id_options.append(temp)
# id_options

In [3]:

# traffic_image_df['timestamp']=traffic_image_df['ImageLink'].apply(lambda x: x.split('/')[3] +' '+ x.split('/')[4].replace('-',''))
# .replace('-','/')
#

# traffic_image_df['filename']=traffic_image_df.apply(lambda x:'%s_%s.jpg'%(x['CameraID'],x['timestamp']),axis=1)



# traffic_image_df['timestamp']=pd.to_datetime(traffic_image_df['timestamp'])